# Generated by Django 4.0.2 on 2023-11-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createcourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='key_reason',
            new_name='soln_reason',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='key',
            new_name='solution',
        ),
    ]
