# Generated by Django 4.0.2 on 2023-11-07 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createcourse', '0002_rename_key_reason_question_soln_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicquestions',
            old_name='key',
            new_name='solution',
        ),
    ]
