# Generated by Django 4.0.2 on 2023-11-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcourse', '0004_question_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicquestions',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
