# Generated by Django 4.0.2 on 2023-11-09 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createcourse', '0006_citation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citation',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='citation',
            old_name='question_id',
            new_name='question',
        ),
    ]
